language: python
python:
  - "3.6.7"
install:
  # - pip install flask
  # - pip install pytest
  # - pip install pytest-cov
  # - pip install flask_restful
  # - pip install Flask-Bcrypt
  # - pip install psycopg2
  # - pip install coveralls
  # - pip install codecov
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=./app/test/v2
after_success:
  - codecov
  - coveralls
  - codeclimate-test-reporter
