language: python
python:
  - "3.6.7"
install:
  # - pip install flask
  # - pip install pytest
  # - pip install pytest-cov
  # - pip install flask_restful
  # - pip install Flask-Bcrypt
  # - pip install psycopg2
  # - pip install coveralls
  # - pip install codecov
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE test_km_ireporter' -U postgres
  - psql -c "CREATE USER k_mbugua WITH PASSWORD 'kmbugua54321';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to k_mbugua;" -U postgres

script:
  - python -m pytest --cov=./app/test/v2

after_success:
  - codecov
  - coveralls
  - codeclimate-test-reporter
